### ISSUE TITLE
Corrigir README

### ISSUE THREAD

**Issue by Dayof** [JotaTri/UIoTDevices#2]
Corrigir erro de markdown na descrição : 

![image](https://user-images.githubusercontent.com/8198348/46381446-bdf51500-c67c-11e8-84d2-6a51a11b1ce7.png)

**Comment by JotaTri** [comment]
Corrigido erro causado por indentação errada no README.md (commit - 3f12606c81a67783877901a42ede75a5ffc28df6 )
